FROM ubuntu:20.04

COPY sources.list /etc/apt/sources.list
COPY pip.conf /root/.pip/pip.conf

RUN apt-get update && apt-get install -yq --no-install-recommends \ 
	python3.8 python3-pip libgomp1 libgl1-mesa-glx libglib2.0-dev && \
	ln -s /usr/bin/python3.8 /usr/bin/python && \
	pip install -U pip && \
	pip install --no-cache-dir \
		opencv-python==4.8.0.76 pillow==10.1.0 pyclipper==1.3.0.post4 \
		shapely==2.0.2 six==1.16.0 onnxruntime==1.16.2 && \
	apt-get autoclean && \
	rm -rf /home/* && \
	rm -rf /var/lib/apt/lists/*
